// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication7.DBContext;

#nullable disable

namespace WebApplication7.Migrations.NewCatalogDb
{
    [DbContext(typeof(NewCatalogDbContext))]
    [Migration("20230723133610_InitialNewCatalogMigration")]
    partial class InitialNewCatalogMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication7.DBContext.NewCatalogfromSystemcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SParentId");

                    b.ToTable("SystemCatalog");
                });

            modelBuilder.Entity("WebApplication7.DBContext.NewCatalogfromSystemcs", b =>
                {
                    b.HasOne("WebApplication7.DBContext.NewCatalogfromSystemcs", "SParentCatalog")
                        .WithMany()
                        .HasForeignKey("SParentId");

                    b.Navigation("SParentCatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
